---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/aywsolution/public_html/scc.aywsolution.com/
      - /bin/rsync -av public/ $DEPLOYPATH
      - export DEPLOYPATH=/home/aywsolution/web_scc/
      - /bin/rsync -av ./ $DEPLOYPATH