---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/gorel/public_html/scc.regionloreto.gob.pe/
      - /bin/rsync -av public/ $DEPLOYPATH
      - export DEPLOYPATH=/home/gorel/web_scc2/
      - /bin/rsync -av ./ $DEPLOYPATH