version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scc_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=gorel_scc
      - DB_USERNAME=gorel_scc
      - DB_PASSWORD=334.-=#123Am
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: scc_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
